### ISSUE TITLE
Migrate Storybook v5 to v6 (via web-dev-server + SB plugin + HMR)

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#183]
## The context

We started the Clever components library with Storybook v5.
8 months later, we did a big migration to adopt CSF for our stories.
This format is really nice!

A few months ago, Storybook released a [new major version: 6.0.0](https://medium.com/storybookjs/storybook-6-0-1e14a2071000).
It contains lots a small improvements and some bigger changes like the [args](https://medium.com/storybookjs/introducing-storybook-args-2dadcdb777cc) and [controls](https://medium.com/storybookjs/storybook-controls-ce82af93e430).

We would like to migrate to this new version and use these new features.

## The problem

Storybook is working hard on improving the performance (especially on 6.1).
However, our experience of using it to build a Web Components library is not satisfying performance wise.

* `npm run storybook:dev` takes 30 seconds to start (on my laptop: 20GB RAM / Core i7-6600U @ 2.60GHz)
* `npm run storybook:build` also takes around 30 seconds to build.
* The time between a code update in a component and the time we see the result in Storybook is around 8 seconds.

### Storybook and Webpack

Storybook is a big project with many modules and components.
It's built with React and TypeScript.
In most cases, this kind of stack requires a setup with bundler and a dev server.
They chose to rely on Webpack for this.

When you work on your code and stories, you start Storybook in dev mode.
This will start Webpack's dev server with a _not-so-simple_ configuration that is common for Storybook's code AND yours.

The benefit is that everything is already there if you need to work with TypeScript, JSX... or if you want to use `import` with images or JSON.
The drawback is that if you need settings different from the default ones, you need to step into [Webpack](https://storybook.js.org/docs/react/configure/webpack#extending-storybooks-webpack-config) or [Babel](https://storybook.js.org/docs/react/configure/babel) customization.
Configuring those tools is not always an easy task so adapting an existing config you know nothing about is not that trivial, you often end up fighting against it.

This default Webpack/Babel setup, dedicated for Storybook's React/TypeScript sources is far from our own context.
Indeed, we made several decisions on this project to stay close to standards and stay away from custom bundler/tools things:

* We don't need old-browser transpilation or polyfills as we only target modern browsers and we don't use early stage unstable JS features
  * Changing the target was yet another customization
* We don't need TypeScript transpilation (though we use TS based tools with our JSDoc)
* We don't need JSX transpilation
* We mostly use ES modules
  * but Webpack 4 output is still custom
* We don't need the non-standard Webpack loader feature to import non JS files like images
* We use standard `new URL('./path/to/asset.svg', import.meta.url)` to refer to assets with relative paths
  * The `import.meta.url` feature is not supported through Webpack 4. It is an ES2020 standard AND has been present in all major browsers for several years. It was quiet difficult to make it work.

In the end our code and stories must shared a Webpack/Babel setup that is really different from what we need and we must inherit from the bad performances of this setup.

### Background

A year ago, the wonderful people at [Open Web Components](https://open-wc.org/) worked on a [prebuilt version of Storybook](https://www.npmjs.com/package/@open-wc/storybook-prebuilt).
More details here: https://dev.to/open-wc/storybook-for-web-components-on-steroids-4h29
The idea was that all the heavy lifting of compiling/bundling Storybook and a set of addons was done once.
Then you could run this prebuilt Storybook with your set of components and stories and your own simple and light config without relying on Webpack if you didn't need to.

The result was really impressive but we were a bit shy to welcome this young project into our code base.
We were worried we could miss new features from Storybook and maybe have less customization powers so we decided to wait.

### Hello Modern Web

Since then, the whole Open Web Components project evolved a lot and a sibling project called [Modern Web](https://modern-web.dev/) appeared.
Both projects feature mature guides and tools for Modern Web in general and also for Web components users.
We share a lot of common principles with the people working on those projects.

Looking at their latest tools, we identified a very interesting combination that would allow us to drop Webpack and have a really fast feedback loop in dev mode:

* web-dev-server: https://modern-web.dev/docs/dev-server/overview/
* Storybook plugin for web-dev-server: https://modern-web.dev/docs/dev-server/plugins/storybook/
* HMR pluging for web-dev-server: https://modern-web.dev/docs/dev-server/plugins/hmr/
  * with Open WC's impl for Web components: https://open-wc.org/docs/development/hot-module-replacement/#installation

With this:

* `npm run storybook:dev` takes 0 seconds to start
* The time between a code update in a component and the time we see the result in Storybook is instant

## The implementation

For this migration, we won't have to touch our source much but we will have to adapt our stories:

* Moving from v5.3.x to v6
* Adapting some stuffs that relied on Webpacks
* Adapting some of our custom Storybook stuffs
* Maybe dropping some addons we were using (for now)

To be continued...

**Comment by hsablonniere** [comment]
## TODO

* [ ] Update image imports in stories
* [ ] Setup english by default
* [ ] Find a way to enable i18n selection
