### ISSUE TITLE
Pricing components [meta]

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#195]
For the new pricing page (and for the console), we need a set of components to display the pricing of our producs.

* [x] [cc-pricing-table](https://github.com/CleverCloud/clever-components/issues/196)
* [x] [cc-pricing-product](https://github.com/CleverCloud/clever-components/issues/205)
* [x] [cc-pricing-product (smart)](https://github.com/CleverCloud/clever-components/issues/238)
* [x] [cc-pricing-cellar](https://github.com/CleverCloud/clever-components/issues/200)
* [x] [cc-pricing-page](https://github.com/CleverCloud/clever-components/issues/206)
* [x] [cc-pricing-estimation](https://github.com/CleverCloud/clever-components/issues/207)
* [x] [cc-pricing-header](https://github.com/CleverCloud/clever-components/issues/208)
