### ISSUE TITLE
Smart components [meta]

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#210]
Now that we implemented the base layer for smart components, it's time to track the TODO for other components:

## Smart definitions

* [ ] addon/cc-addon-backups
* [ ] addon/cc-addon-linked-apps
* [ ] addon/cc-addon-admin
* [ ] addon/cc-addon-credentials
* [ ] addon/cc-addon-features
* [ ] addon/cc-elasticsearch-info
* [ ] addon/cc-header-addon
* [ ] env-var/cc-env-var-form (env-vars)
* [ ] env-var/cc-env-var-form (addon readonly)
* [ ] map/cc-logsmap
* [ ] overview/cc-header-app
* [ ] overview/cc-header-orga
* [ ] overview/cc-tile-consumption
* [ ] overview/cc-tile-deployments
* [ ] overview/cc-tile-instances
* [ ] overview/cc-tile-requests
* [ ] overview/cc-tile-scalability
* [ ] overview/cc-tile-status-codes
* [ ] overview/cc-tile-requests
* [ ] overview/cc-tile-status-codes
* [ ] saas/cc-heptapod-info

## Other details

* Proper event bus system to hook with even API
* Proper polling system (used in some situations like instances)
