### ISSUE TITLE
Implement cc-input-number

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#211]
## Context

We need an `<input type=number>` with -/+ buttons.
We won't be using the existing `<cc-input-text>` because it already does a lot of things and they're not really useful for input number.

## Requirements

```
-----------------
| - |    10 | + |
-----------------
```

* Needs to look like `<cc-input-text>` (same borders, spacing...)
* `<input type=number>` under the hood
* Text aligned to the right by default (we may consider a CSS custom prop)
* We need to hide the arrow keys that some browser display for such fields
* (-) minus button on the left of the field
* (+) plus button on the right of the field

## Inputs (props)

* label
* value
* min
* max
* step
* readonly
* disabled

## Outputs (events)

* value

**Comment by Galimede** [comment]
# TODO : 

- [ ] Handle min, max, step
- [ ] Pattern attribute for mobile keyboard input (https://css-tricks.com/finger-friendly-numerical-inputs-with-inputmode/)
- [ ] Update docs 
- [ ] Check type of the event (when it's not a number (valueAsNumber ?))

**Comment by Galimede** [comment]
# Notes : 
* Step is acting weirdly when used with the keyboard, for instance if we input 55 and do a step of 10 and want to go down it will first go to 50 then to 40 if we want to go down again. Same if we do it twice the other way it will first go to 60 then to 70. 
* When handling min, max we should maybe change the focus color to red when there is an error as it's not really visible 
-> Or should we just simply enforce min,max so that when it's not in the range we would just make it go back to the min if it's below it or max if it's above it ? 
* Pattern attribute with mobile keyboard doesn't seem necessary (I've tested it myself and the number keyboard already appears) 
* When we have either a step or not if we go down to 0 with the keyboard the input just disappear, should we just enforce 0 as the initial value when there's none to prevent that ?

**Comment by hsablonniere** [comment]
In general, I want to reproduce the native behaviour of input[type=number].

> Step is acting weirdly when used with the keyboard, for instance if we input 55 and do a step of 10 and want to go down it will first go to 50 then to 40 if we want to go down again. Same if we do it twice the other way it will first go to 60 then to 70.

I just did a few tests and it seems like step is related to min (even when it's not set) so if you set a step of 10, it's relative to min (default to 9) and not to current value.

> When handling min, max we should maybe change the focus color to red when there is an error as it's not really visible
> -> Or should we just simply enforce min,max so that when it's not in the range we would just make it go back to the min if it's below it or max if it's above it ?

Seems like the browser already has default styles and default tooltip when there's an error.

![Capture d’écran_2021-03-17_11-32-02](https://user-images.githubusercontent.com/236342/111454390-e1a95a00-8714-11eb-9cec-37310a8b930e.png)
![Capture d’écran_2021-03-17_11-28-02](https://user-images.githubusercontent.com/236342/111454403-e3731d80-8714-11eb-8c46-39c40420c0e9.png)

Chrome doesn't have a style but it has the tooltip.

I see two solutions:

* A red focus ring instead of the current color
* A warning icon inside the input left aligned (but it may look weird when the minus button is here)

Can you try both (red focus ring + warning icon) and post screenshots (with and without buttons in the case of the warning icon)?

> Pattern attribute with mobile keyboard doesn't seem necessary (I've tested it myself and the number keyboard already appears)

Have you tried Android only? Maybe it's for old versions...

> When we have either a step or not if we go down to 0 with the keyboard the input just disappear, should we just enforce 0 as the initial value when there's none to prevent that ?
@hsablonniere WDYT?

What do you mean it disappears?

**Comment by hsablonniere** [comment]
I'm considering aligning the content at the center. Could we do right aligned by default et provide a `--cc-input-number-align` custom property?

**Comment by Galimede** [comment]
> I just did a few tests and it seems like step is related to min (even when it's not set) so if you set a step of 10, it's relative to min (default to 9) and not to current value.

Will investigate and give it the native behavior logic for the controls as it's the case causing trouble :+1: 

> Can you try both (red focus ring + warning icon) and post screenshots (with and without buttons in the case of the warning icon)?

Will do, I will comment with some screenshots when it's ready :wink: 

> Have you tried Android only? Maybe it's for old versions...

I have also tried it on IPad, it's the larger version of the number keyboard, will do some more tests tho :nerd_face: 

> I'm considering aligning the content at the center. Could we do right aligned by default et provide a `--cc-input-number-align` custom property?

Sure :smile:
