### ISSUE TITLE
cc-input-*: use default font family instead of monospace

### ISSUE THREAD

**Issue by florian-sanders-cc** [CleverCloud/clever-components#453]
`cc-input-*` uses the monospace font-family which forces us to override it everytime we use this component to use the default font family instead.
It should be done the other way around, `cc-input-*` should use the default family and the few components that need monospace should override the default font family.

# TODO:

- [x] list all components that need monospace instead of default,
- [x] change font-family to default inside the `cc-input-*` components,
- [x] force monospace font in components listed in step 1.

# Components that need monospace font

- [x] cc-addon-backups (command fields)
- [x] env-var-create

**Comment by florian-sanders-cc** [comment]
Might not be as simple as I thought. We may have to provide a CSS part so that people can easily change input font-family ?

**Comment by hsablonniere** [comment]
> Might not be as simple as I thought. We may have to provide a CSS part so that people can easily change input font-family ?

I think we can expose a `--cc-input-text-font-family` and `--cc-input-number-font-family` or just a `--cc-input-font-family`.

Changing this kind of default is a breaking change BTW.
