### ISSUE TITLE
CDN UI: display info related to the theme stylesheet

### ISSUE THREAD

**Issue by florian-sanders-cc** [CleverCloud/clever-components#508]
# Context 

Following #403 / #472, the common CSS for our components (the theme) is now provided through a CSS file instead of a JS file.

This means people using our components need to use this CSS file:
* by relying on a `<link ref="stylesheet">` tag,
* or a CSS `@import`.

This issue can only be handled after we have updated the CDN back end so that it can serve the CSS file corresponding to a specific version of the component. (see issue [smart CDN #2](https://github.com/CleverCloud/clever-components-cdn/issues/2)).

# Goals

The CDN UI needs to display the end point serving this CSS file (the specific endpoint would depend on the components version).

# TODO

- [ ] show the relevant sections from the cdn-ui index file (they are ready but hidden at the moment).
- [ ] only show if manifest version === 2
- [ ] update the ["How to use the components theme?"](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%93%8C-docs-how-to-use-the-components-theme--page) doc with a Smart CDN section.
