### ISSUE TITLE
[meta] state+smart migration

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#708]
## Context

Now that we settled for a new design of the components' states and their smart definitions without RxJS, we need to update the existing components.

Here are the benefits:

* Smaller code to load because we no longer need RxJS
* One less dependency to maintain
* Less complex code to maintain (compared to the new design)

These aren't that impactful for our users and should be done progressively.
The problem is that each state refactor will create a breaking change for the components.

Is it such a big deal?

## TODO:

* [ ] cc-invoice
  * cc-invoice.smart
* [ ] cc-env-var-form
  * cc-env-var-form.smart-exposed-config
  * cc-env-var-form.smart-env-var-addon
  * cc-env-var-form.smart-config-provider
* [x] cc-pricing-product (WIP through @florian-sanders-cc work on pricing components)
  * cc-pricing-product.smart-runtime
  * cc-pricing-product.smart-addon
* [ ] cc-article-list
  * cc-article-list.smart
* [x] cc-pricing-page (WIP through @florian-sanders-cc work on pricing components)
  * cc-pricing-page.smart
* [x] cc-pricing-product-consumption (WIP through @florian-sanders-cc work on pricing components)
  * cc-pricing-product-consumption.smart
* [ ] cc-invoice-list
  * cc-invoice-list.smart
* [ ] cc-grafana-info
  * cc-grafana-info.smart
* [ ] cc-tile-status-codes
  * cc-tile-status-codes.smart
* [x] cc-addon-linked-apps
  * cc-addon-linked-apps.smart
* [ ] cc-jenkins-info
    * cc-jenkins-info.smart

NOTE: This issue only tracks components that have smart definitions. Those who have a "legacy" state interface but not smart definition will be updated later.

**Comment by roberttran-cc** [comment]
About splitting the migration into multiple PRs or not, I think I prefer multiple PRs: exchanges will be easier, as the topic can be quite tricky.

**Comment by florian-sanders-cc** [comment]
I vote Bob :wink: (multiple PRs)

**Comment by florian-sanders-cc** [comment]
closing this issue because we have a milestone to track progress (see https://github.com/CleverCloud/clever-components/milestone/6)
