### ISSUE TITLE
Web Dev Server: upgrade & update config

### ISSUE THREAD

**Issue by florian-sanders-cc** [CleverCloud/clever-components#812]
## Context

The Web Dev Server poject just released a version 0.3.0.

This version contains a change that makes the following config option redundant since it's the default now:
```js
nodeResolve: {
  exportConditions: ['development'],
},
```

## TODO

- [ ] Switch Web Dev Server dependency to `^0.3.0` within the `package.json` (since the dependency hasn't reach v1 yet, we can't rely on the carret usage to auto install minor versions).
- [ ] run `npm install`
- [ ] Change the WDS config as follows:
```js
nodeResolve: true,
```
