### ISSUE TITLE
Publish components on a CDN (late todo & improvements)

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#82]

**Comment by hsablonniere** [comment]
Lots of progress has been done on this using rollup. More to follow soon.

**Comment by hsablonniere** [comment]
Reminder, right now, the beta solution is used here:

* ccadmin
* keycloak

**Comment by hsablonniere** [comment]
Webperf tests helped us to fine tune optimizations.
Seems like the best case we can have is:

* HTTP/2
* Rollup Treeshaking
* No Rollup scope hoist
* Manual chunk groups to limit nb of requests
* Manual shim for unused stuffs
* Manual hoisting with reverse order tree
  * Static imports for i18n stuffs
  * Dynamic imports for components

TODO:

* Custom Rollup plugin for deps
* [ ] Setup Rollup build
* [ ] Setup sync/upload to Cellar
* [ ] Setup dynamic endpoint

**Comment by hsablonniere** [comment]
Don't forget about CSS!

**Comment by hsablonniere** [comment]
Details TODO:

* [ ] Decide on the cellar domain
* [ ] Decide on the dynamic endpoint domain
* [ ] Setup a CDN in front of the cellar
* [ ] Setup a CDN in front of the dynamic endpoint
* [ ] Write some docs
* [ ] Update ccadmin
* [ ] Update keycloak

**Comment by hsablonniere** [comment]
Almost done through #177

**Comment by hsablonniere** [comment]
About the separated system for tests/previews:

I've been thinking about reusing the same Cellar + CF worker but it would compromise security as it would mean using the same creds to edit/delete production assets and preview assets.

So here's the deal:

* [ ] Create a new Cellar add-on for previews
* [ ] Adapt the CF worker code to support previews with branch-names (invalid semver)
* [ ] Create a new CF worker with `preview-components.clever-cloud.com`
* [ ] Configure the glue for the domains etc...
