### ISSUE TITLE
migrating to our new state structure

### ISSUE THREAD

**Issue by florian-sanders-cc** [CleverCloud/clever-components#946]
## Context

As explained in #944 we have agreed on a consistent way to build the state of our components.

We still have many components where impossible states are still possible and some components with the "old" way of structuring state.

Here is a list of all the components to tackle.

### DONE (or almost done)

- [x] cc-addon-admin
- [x] cc-matomo-info
- [x] cc-article-card => should we go for simple skeleton boolean explicitly set instead?
- [x] cc-doc-card => should we go for simple skeleton boolean explicitly set instead?
- [x] cc-doc-list
- [x] cc-elasticsearch-info
- [x] cc-heptapod-info
- [x] cc-invoice-table => should we go for simple skeleton boolean explicitly set instead?
- [x] cc-addon-features (issue with skeleton anyway)
- [x] cc-addon-backups
- [x] cc-header-addon (**needs rebase cc-zone**)
- [x] cc-zone  => should we go for simple skeleton boolean explicitly set instead?
- [x] cc-header-orga => has a state but needs to be changed to the new model
- [x] cc-tcp-redirection  => has a state but needs to be changed to the new model
- [x] cc-header-app
- [x] cc-tcp-redirection-form => has a state but needs to be changed to the new model
- [x] cc-tile-scalability
- [x] cc-zone-input
- [x] cc-tile-requests

### TODO 

- [x] cc-tile-metrics  => has a state but needs to be changed to the new model
- [ ] cc-addon-credentials
- [ ] cc-logsmap => already has loading / error, do we want state?
- [ ] cc-map => already has loading / error, do we want state?
- [x] cc-email-list => has a state but needs to be changed to the new model
- [x] cc-ssh-key-list => has a state but needs to be changed to the new model
- [x] cc-orga-member-list => has a state but needs to be changed to the new model
- [x] cc-orga-member-card => has a state but needs to be changed to the new model

### WON'T DO

- [ ] cc-pricing-header => interesting because without prefix it would feel weird?
- [ ] cc-pricing-product => has a state but needs to be changed to the new model
- [ ] cc-pricing-product-consumption => has a state but needs to be changed to the new model

**Comment by florian-sanders-cc** [comment]
Ready to PR:

- [ ] cc-addon-admin
- [ ] cc-matomo-info
- [ ] cc-article-card => should we go for simple skeleton boolean explicitly set instead?
- [ ] cc-doc-card => should we go for simple skeleton boolean explicitly set instead?
- [ ] cc-doc-list
- [ ] cc-elasticsearch-info
- [ ] cc-heptapod-info
- [ ] cc-invoice-table => should we go for simple skeleton boolean explicitly set instead?
- [ ] cc-addon-features (issue with skeleton anyway)
- [ ] cc-addon-backups
- [ ] cc-header-addon (**needs rebase cc-zone**)
- [ ] cc-zone  => should we go for simple skeleton boolean explicitly set instead?
- [ ] cc-email-list => has a state but needs to be changed to the new model
- [ ] cc-header-orga => has a state but needs to be changed to the new model
- [ ] cc-tcp-redirection  => has a state but needs to be changed to the new model
- [ ] cc-header-app
- [ ] cc-tcp-redirection-form => has a state but needs to be changed to the new model
- [ ] cc-tile-scalability

**Comment by florian-sanders-cc** [comment]
closing this issue because we have a milestone to track progress (see https://github.com/CleverCloud/clever-components/milestone/6)
